In [9]:
from fastai.collab import *
from fastai.tabular.all import *
set_seed(42)

In [10]:
import numpy as np
import pandas as pd

Importing the data

In [11]:
path = untar_data(URLs.ML_100k)

Reading the data

In [12]:
rating_df = pd.read_csv(path/'u.data',delimiter = '\t', header = None, names = ['user','movie','rating','timestamp'])
rating_df.head()

   user  movie  rating  timestamp
0   196    242       3  881250949
1   186    302       3  891717742
2    22    377       1  878887116
3   244     51       2  880606923
4   166    346       1  886397596

Reading the dataframe having a movie title

In [13]:
movies_df = pd.read_csv(path/'u.item', delimiter='|',encoding='latin-1',usecols=(0,1), names=('movie','title'), header=None)
movies_df.head()

   movie              title
0      1   Toy Story (1995)
1      2   GoldenEye (1995)
2      3  Four Rooms (1995)
3      4  Get Shorty (1995)
4      5     Copycat (1995)

Merging the movies and rating dataframe

In [15]:
rating_df = rating_df.merge(movies_df)  #merging the rating and movie dataframe
rating_df.head()

   user  movie  rating  timestamp                       title
0   196    242       3  881250949                Kolya (1996)
1   186    302       3  891717742    L.A. Confidential (1997)
2    22    377       1  878887116         Heavyweights (1994)
3   244     51       2  880606923  Legends of the Fall (1994)
4   166    346       1  886397596         Jackie Brown (1997)

Creation of dataloaders

In [19]:
dls = CollabDataLoaders.from_df(rating_df,item_name = 'title' , bs = 64) #here we are creating a dataloaders based on userID, movie_title as item  and the movie_rating done by the user
dls.show_batch()